//
//  main.m
//  SplitIt
//
//  Created by Jaimin Doshi on 4/5/14.
//  Copyright (c) 2014 Jaimin Doshi. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <Firebase/Firebase.h>

#import "NYUAppDelegate.h"

int main(int argc, char * argv[])
{
    @autoreleasepool {
        
        NSLog(@"HI");
        //REMOVING EVERYTHING FROM DATABASE
        //        Firebase* f=[[Firebase alloc]initWithUrl:@"https://splitbill.firebaseio.com/"];
        //        [f removeValue];
//        __block double total=0;
//        Firebase* f=[[Firebase alloc]initWithUrl:@"https://splitbill.firebaseio.com/78/JAy/"];
//        [f observeEventType:FEventTypeValue withBlock:^(FDataSnapshot *snapshot) {
//            if (![snapshot.name isEqualToString:@"tax"] && ![snapshot.name isEqualToString:@"tip"] ){
//                NSString* foodValue= snapshot.value;
//                (total)+=[foodValue doubleValue];
//                NSLog(@"%0.2f", total);
//            }
//        }];
        
 
//        NSMutableArray *users = [[NSMutableArray alloc]init]; // allocating the users array
//        Firebase* f=[[Firebase alloc]initWithUrl:@"https://splitbill.firebaseio.com/"];
//        __block NSData *data;
//        [f observeEventType:FEventTypeValue withBlock:^(FDataSnapshot *snapshot) {
//            //NSString *userName = snapshot.value;
//            //[users addObject:[NSString stringWithFormat:@"%@", snapshot.name]];
//            //[users addObject:userName];
//            //NSLog(@"%@", snapshot.name);
//            //NSLog(userName);
//            //NSString* firstName = snapshot.value[@"10"];
//            data = snapshot.valueInExportFormat;
//            
//            //NSLog(@"%@", data);
//            NSError *error;
//            NSDictionary *json = [NSJSONSerialization JSONObjectWithData:data options:0 error:&error];//response object is your response from server as NSData
//            
//            NSArray *tableValues = json[@"10"];
//            for (NSDictionary *dictionary in tableValues) {
//                NSString* fname = [dictionary objectForKey:@"name"];
//                
//            }
//            
//            
//        }];
        //


        
        
        
//        Firebase* ref=[f childByAppendingPath:@"Shalin"];
//        [ref removeValue];
        //-----------------------
//        // Generate a reference to a new location with childByAutoId
//        Firebase* newPushRef = [listRef childByAutoId];
//
//        
//        // Get the name generated by push
//        NSString* pushedName = newPushRef.name;
        
        
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([NYUAppDelegate class]));
    }
}
