//
//  main.m
//  SplitIt
//
//  Created by Jaimin Doshi on 4/5/14.
//  Copyright (c) 2014 Jaimin Doshi. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <Firebase/Firebase.h>

#import "NYUAppDelegate.h"

int main(int argc, char * argv[])
{
    @autoreleasepool {
        
        NSLog(@"HI");
        // Create a reference to a Firebase location
        Firebase* f = [[Firebase alloc] initWithUrl:@"https://cs394.firebaseio.com/"];
        
        // Write data to Firebase
        //[f setValue:@"Do you have data? You'll love Firebase."];
        [[[[f childByAppendingPath:@"11"] childByAppendingPath:@"Jay"] childByAppendingPath:@"pizza"] setValue:[NSNumber numberWithInt:11]];
        
        
        
         
         //setValue:[NSNumber numberWithInt:11]];
//        [f childByAutoId ];
//        [f setValue:@{@"226": @""}];
        
//        // Read data and react to changes
//        [f observeEventType:FEventTypeValue withBlock:^(FDataSnapshot *snapshot) {
//            NSLog(@"%@ -> %@", snapshot.name, snapshot.value);
//        }];
        //-----------------------
//        // Generate a reference to a new location with childByAutoId
//        Firebase* newPushRef = [listRef childByAutoId];
//        
//        // Set some data to the generated location
//        [newPushRef setValue:@{@"user_id": @"wilma", @"text": @"Hello"}];
//        
//        // Get the name generated by push
//        NSString* pushedName = newPushRef.name;
        
        
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([NYUAppDelegate class]));
    }
}
